-- DROP TABLE IF EXISTS EXPENSE_CATEGORY;
-- DROP TABLE IF EXISTS EXPENSES;
-- DROP TABLE IF EXISTS CATEGORIES;

-- CREATE TABLE CATEGORIES (
--    ID INT PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL
--);

-- CREATE TABLE EXPENSES (
--     ID INT PRIMARY KEY,
--     DESCRIPTION VARCHAR(255) NOT NULL,
--     AMOUNT DECIMAL(10,2) NOT NULL,
--     DATE DATE NOT NULL
-- );
CREATE TABLE EXPENSE_CATEGORY (
	EXPENSE_ID BIGINT NOTNULL,
    CATEGORY_ID BIGINT NOTNULL,   
    PRIMARY KEY (EXPENSE_ID, CATEGORY_ID),   
    FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSES(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

-- Dummy categories
INSERT INTO CATEGORY (NAME) VALUES ('Food');
INSERT INTO CATEGORY (NAME) VALUES ('Transport');
INSERT INTO CATEGORY (NAME) VALUES ('Utilities');
INSERT INTO CATEGORY (NAME) VALUES ('Entertainment');
INSERT INTO CATEGORY (NAME) VALUES ('Health');
INSERT INTO CATEGORY (NAME) VALUES ('Education');
INSERT INTO CATEGORY (NAME) VALUES ('Shopping');
INSERT INTO CATEGORY (NAME) VALUES ('Travel');
INSERT INTO CATEGORY (NAME) VALUES ('Savings');
INSERT INTO CATEGORY (NAME) VALUES ('Gifts');
INSERT INTO CATEGORY (NAME) VALUES ('Insurance');
INSERT INTO CATEGORY (NAME) VALUES ('Pets');
INSERT INTO CATEGORY (NAME) VALUES ('Home');
INSERT INTO CATEGORY (NAME) VALUES ('Car');
INSERT INTO CATEGORY (NAME) VALUES ('Subscriptions');
INSERT INTO CATEGORY (NAME) VALUES ('Charity');
INSERT INTO CATEGORY (NAME) VALUES ('Childcare');
INSERT INTO CATEGORY (NAME) VALUES ('Personal Care');
INSERT INTO CATEGORY (NAME) VALUES ('Books');
INSERT INTO CATEGORY (NAME) VALUES ('Miscellaneous');

-- Dummy expenses
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Lunch at cafe', 12.50, '2025-08-01');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Bus ticket', 2.75, '2025-08-02');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Electricity bill', 45.00, '2025-07-30');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Movie night', 15.00, '2025-08-01');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Pharmacy purchase', 8.20, '2025-08-03');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Online course fee', 120.00, '2025-07-15');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Groceries', 55.30, '2025-08-02');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Flight ticket', 350.00, '2025-07-20');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Monthly savings deposit', 200.00, '2025-08-01');
INSERT INTO EXPENSE (DESCRIPTION, AMOUNT, DATE) VALUES ('Birthday gift', 30.00, '2025-08-03');
